; local php.ini config
date.timezone="UTC"
upload_max_filesize = 100M
post_max_size = 0
max_file_uploads = 500

; extensions
extension=gd.so
extension=intl.so
extension=mysqli.so
extension=opcache.so
extension=pdo.so
extension=pdo_mysql.so
extension=zip.so
extension=mbstring.so
